# -*- coding: utf-8 -*-
"""random_forest_sklearn_iris.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kRunlxlsjI15ctb555l8RQGHap1UpjDW
"""

from sklearn import datasets  
from sklearn.datasets import load_iris 
from sklearn.ensemble import RandomForestClassifier  
from sklearn.metrics import  accuracy_score ,confusion_matrix

iris = load_iris()

iris.target_names

iris.feature_names

X = iris.data
y = iris.target

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 42)

clf = RandomForestClassifier(n_estimators = 100)  
  
clf.fit(X_train, y_train)
  
y_pred = clf.predict(X_test)
  
print("accuracy of model: {}%".format(accuracy_score(y_test, y_pred).round(4)*100))

clf.predict([[3, 3, 2, 2]])

print(confusion_matrix(y_test, y_pred))